### PR TITLE
Added code to set session variable for custom stax header: x-stax-ses…

### PR DESCRIPTION
**Pull request by pramireddy**
Added code to set session variable for custom stax editor

### CODE REVIEW

**Comment by ravi-methods** [comment]
Is this still required @pramireddy ?

**Comment by pramireddy** [comment]
> Is this still required @pramireddy ?

Not sure whethet it's 

> Is this still required @pramireddy ?

@ravi-methods @ryanbarlowmethods Not sure whether it's required? If not then we need to remove the code for header: "X-STAX-SessionId".

**Comment by ryanbarlowmethods** [comment]
Is still needed for future yeh -approving

**Review by ryanbarlowmethods — APPROVED** [review]

**Comment by bmatthews-DFE** [comment]
Closing due to inactivity

**Pull request closed without merging**
